[project]
name = "gb-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "clickhouse-connect>=1.6.0",
    "fastapi>=0.141.1",
    "pillow>=12.3.0",
    "uvicorn>=0.52.1",
]

[project.scripts]
gb-client = "gb_client:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
